/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { GeneratedBlueprint, GeneratedBlueprintInterface } from "../GeneratedBlueprint.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220a10f1dc1d188aceb71e1ce7fe716b20cfed0a131a7d29ef42590e9f327c16d9564736f6c63430008180033";

  
      type GeneratedBlueprintConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: GeneratedBlueprintConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class GeneratedBlueprint__factory extends ContractFactory {
    
      constructor(...args: GeneratedBlueprintConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<GeneratedBlueprint & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): GeneratedBlueprint__factory {
      return super.connect(runner) as GeneratedBlueprint__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): GeneratedBlueprintInterface {
      return new Interface(_abi) as GeneratedBlueprintInterface;
    }
    
    override attach(address: string | Addressable): GeneratedBlueprint {
      return super.attach(address) as GeneratedBlueprint;
    }
  static connect(address: string, runner?: ContractRunner | null): GeneratedBlueprint {
      return new Contract(address, _abi, runner) as unknown as GeneratedBlueprint;
    }
  }

  
  