/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as glorgSol from './Glorg.sol/index.js';
export { Lock__factory } from './Lock__factory.js';
export { MyContract__factory } from './MyContract__factory.js';