/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as glorgSol from './Glorg.sol/index.js';
export type { glorgSol };
export type { Lock } from './Lock.js';
export type { MyContract } from './MyContract.js';
export * as factories from './factories/index.js';
export type { MyContract } from './Glorg.sol/MyContract.js';
export { MyContract__factory } from './factories/Glorg.sol/MyContract__factory.js';
export { Lock__factory } from './factories/Lock__factory.js';